import {
  pgTable,
  uuid,
  text,
  integer,
  numeric,
  timestamp,
  doublePrecision,
} from "drizzle-orm/pg-core";

export const places = pgTable("places", {
  id: uuid("id").primaryKey(),
  name: text("name").notNull(),
  citySlug: text("city_slug").notNull(),
  cityUrl: text("city_url").notNull(),
  listPosition: integer("list_position"),
  streetAddress: text("street_address").notNull(),
  addressLocality: text("address_locality"),
  addressRegion: text("address_region"),
  postalCode: text("postal_code"),
  addressCountry: text("address_country"),
  telephone: text("telephone"),
  website: text("website"),
  mapsUrl: text("maps_url"),
  googlePlaceId: text("google_place_id"),
  servesCuisine: text("serves_cuisine").array().notNull(),
  ratingValue: numeric("rating_value", { precision: 3, scale: 2 }),
  reviewCount: integer("review_count"),
  source: text("source").notNull(),
  sourceUrl: text("source_url").notNull(),
  scrapedAt: timestamp("scraped_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  lat: doublePrecision("lat"),
  lng: doublePrecision("lng"),
});
